version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coffee_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

volumes:
  postgres_data: